name: disx-dev

services:
  disx-db-dev:
    container_name: disx-db-dev
    image: postgres:latest
    ports:
      - 3011:3011
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 3011
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  comment-db-dev:
    container_name: comment-db-dev
    image: postgres:latest
    ports:
      - 3021:3021
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 3021
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # keycloak-db:
  #   image: postgres:latest
  #   ports:
  #     - 3031:3031
  #   environment:
  #     PGPORT: 3031 
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres

  # keycloak:
  #   image: quay.io/keycloak/keycloak:25.0.0
  #   ports:
  #     - "3030:3030"
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   command: start-dev --http-port=3030
